export const FULL_WIDTH = window.innerWidth <= 1920 ? 1920 : window.innerWidth;
export const FULL_HEIGHT =
  window.innerHeight <= 1080 ? 1080 : window.innerHeight;

export const SUN_CHARACTERISTICS = {
  SIZE: 10,
  MASS: 1.989e30,
  DEFAULT_POSITION: {
    x: FULL_WIDTH / 2,
    y: FULL_HEIGHT / 2,
  },
};

export const EARTH_CHARACTERISTICS = {
  SIZE: SUN_CHARACTERISTICS.SIZE / 3,
  MASS: SUN_CHARACTERISTICS.MASS / 330000,
  DISTANCE: 1.4981e11,
  DEFAULT_POSITION: {
    x: FULL_WIDTH / 2.3,
    y: FULL_HEIGHT / 2,
  },
};

export const MOON_CHARACTERISTICS = {
  SIZE: EARTH_CHARACTERISTICS.SIZE / 2,
  MASS: EARTH_CHARACTERISTICS.MASS / 81,
  DISTANCE: 3.84e8,
  DEFAULT_POSITION: {
    x: EARTH_CHARACTERISTICS.DEFAULT_POSITION.x - 0.00257,
    y: FULL_HEIGHT / 2,
  },
};

export const MERCURY_CHARACTERISTICS = {
  SIZE: EARTH_CHARACTERISTICS.SIZE / 2,
  MASS: EARTH_CHARACTERISTICS.MASS / 20,
  DISTANCE: 6.8538e10,
  DEFAULT_POSITION: {
    x:
      0.61 * SUN_CHARACTERISTICS.DEFAULT_POSITION.x +
      0.39 * EARTH_CHARACTERISTICS.DEFAULT_POSITION.x,
    y: FULL_HEIGHT / 2,
  },
};

export const VENUS_CHARACTERISTICS = {
  SIZE: EARTH_CHARACTERISTICS.SIZE,
  MASS: EARTH_CHARACTERISTICS.MASS / 1.23,
  DISTANCE: 1.0748e11,
  DEFAULT_POSITION: {
    x:
      0.277 * SUN_CHARACTERISTICS.DEFAULT_POSITION.x +
      0.723 * EARTH_CHARACTERISTICS.DEFAULT_POSITION.x,
    y: FULL_HEIGHT / 2,
  },
};

export const JUPITER_CHARACTERISTICS = {
  SIZE: SUN_CHARACTERISTICS.SIZE / 2,
  MASS: SUN_CHARACTERISTICS.MASS / 1000,
  DISTANCE: 7.7433e11,
  DEFAULT_POSITION: {
    x:
      5.2 * EARTH_CHARACTERISTICS.DEFAULT_POSITION.x -
      4.2 * SUN_CHARACTERISTICS.DEFAULT_POSITION.x,
    y: FULL_HEIGHT / 2,
  },
};
