import {
  SUN_CHARACTERISTICS,
  MERCURY_CHARACTERISTICS,
  VENUS_CHARACTERISTICS,
  EARTH_CHARACTERISTICS,
  MOON_CHARACTERISTICS,
  JUPITER_CHARACTERISTICS,
} from './planets-characteristics';

export const planets = [
  {
    id: 1,
    name: 'Sun',
    mass: SUN_CHARACTERISTICS.MASS,
    position: SUN_CHARACTERISTICS.DEFAULT_POSITION,
    velocity: { x: 0, y: 0 },
    color: 'orange',
    size: SUN_CHARACTERISTICS.SIZE,
    strokeColor: 'red',
  },
  {
    id: 2,
    name: 'Mercury',
    mass: MERCURY_CHARACTERISTICS.MASS,
    position: MERCURY_CHARACTERISTICS.DEFAULT_POSITION,
    velocity: { x: 0, y: 0.000039 },
    color: 'grey',
    size: MERCURY_CHARACTERISTICS.SIZE,
    strokeColor: 'red',
  },
  {
    id: 3,
    name: 'Venus',
    mass: VENUS_CHARACTERISTICS.MASS,
    position: VENUS_CHARACTERISTICS.DEFAULT_POSITION,
    velocity: { x: 0, y: 0.00003 },
    color: 'yellow',
    size: VENUS_CHARACTERISTICS.SIZE,
    strokeColor: 'red',
  },
  {
    id: 4,
    name: 'Earth',
    mass: EARTH_CHARACTERISTICS.MASS,
    position: EARTH_CHARACTERISTICS.DEFAULT_POSITION,
    velocity: { x: 0, y: 0.000026 },
    color: 'blue',
    size: EARTH_CHARACTERISTICS.SIZE,
    strokeColor: '61dafb',
  },
  {
    id: 5,
    name: 'Jupiter',
    mass: JUPITER_CHARACTERISTICS.MASS,
    position: JUPITER_CHARACTERISTICS.DEFAULT_POSITION,
    velocity: { x: 0, y: 0.00001 },
    color: 'brown',
    size: JUPITER_CHARACTERISTICS.SIZE,
    strokeColor: 'red',
  },
  // {
  //   id: 6,
  //   name: 'Moon',
  //   mass: MOON_MASS,
  //   position: MOON_DEFAULT_POSITION,
  //   velocity: { x: 0, y: 0.00002599 },
  //   color: 'c6c3b5',
  //   size: MOON_SIZE,
  //   strokeColor: '61dafb',
  // },
];
